# Sejarah Klasifikasi
Model klasifikasi dalam konteks pembelajaran mesin (machine learning) adalah hasil pengembangan dan penelitian oleh banyak ilmuwan dan peneliti dalam bidang komputer, statistik, dan ilmu data selama beberapa dekade. Tidak ada satu individu atau pendiri tunggal yang dapat diidentifikasi sebagai pendiri model klasifikasi.

Model klasifikasi yang paling awal, seperti model regresi logistik dalam statistik, telah ada sejak awal abad ke-20. Namun, dalam konteks pembelajaran mesin modern, banyak ilmuwan dan peneliti telah berkontribusi untuk mengembangkan berbagai algoritma klasifikasi dan model seperti Support Vector Machines (SVM), Naive Bayes, Decision Trees, Random Forests, dan Deep Learning, yang digunakan secara luas dalam berbagai aplikasi.

Jadi, model klasifikasi adalah hasil dari penelitian kolaboratif selama bertahun-tahun oleh berbagai individu dan kelompok penelitian di seluruh dunia, dan tidak dapat diatribusikan kepada satu pendiri tunggal. Hal ini mencerminkan sifat perkembangan ilmu pengetahuan dan teknologi yang melibatkan kontribusi dari banyak individu dan komunitas.

## Pengertian Klasifikasi
Klasifikasi adalah salah satu tugas penting dalam pembelajaran mesin dan statistik yang melibatkan pengelompokan atau penempatan objek data ke dalam kategori atau kelas tertentu berdasarkan fitur atau karakteristik tertentu. Tujuan utama dari klasifikasi adalah untuk memprediksi atau mengidentifikasi kelas atau label yang sesuai untuk setiap objek data berdasarkan informasi yang ada.

Contoh umum klasifikasi termasuk:

1. Klasifikasi Email: Misalnya, memprediksi apakah sebuah email adalah spam atau bukan spam berdasarkan isinya.
2. Klasifikasi Gambar: Mengidentifikasi objek dalam gambar, seperti mengklasifikasikan gambar sebagai kucing, anjing, mobil, atau lainnya.
3. Klasifikasi Medis: Mendiagnosis penyakit berdasarkan data medis pasien, seperti mengklasifikasikan apakah seorang pasien memiliki penyakit jantung atau tidak berdasarkan hasil tes.
4. Klasifikasi Sentimen: Menentukan apakah suatu teks atau ulasan memiliki sentimen positif, negatif, atau netral.
5. Klasifikasi Kejahatan: Mengklasifikasikan laporan kejahatan ke dalam jenis-jenis kejahatan tertentu.
5. Klasifikasi Pekerjaan: Mengklasifikasikan pekerjaan berdasarkan deskripsi pekerjaan atau kualifikasi.

Untuk melakukan klasifikasi, model pembelajaran mesin seperti Support Vector Machines (SVM), Naive Bayes, Decision Trees, Random Forests, dan Deep Learning (misalnya, menggunakan jaringan saraf tiruan) dapat digunakan. Model-model ini diajar untuk memahami pola dalam data pelatihan yang digunakan untuk melatih model, dan kemudian model tersebut digunakan untuk memprediksi kelas atau label untuk data baru yang belum pernah dilihat sebelumnya.

Klasifikasi adalah komponen kunci dalam banyak aplikasi pembelajaran mesin dan memiliki banyak manfaat dalam pengambilan keputusan dan otomatisasi tugas-tugas yang melibatkan pengelompokan data berdasarkan atribut tertentu.

## Support Vector Machine (SVM)
Algoritma SVM merupakan model pembelajaran terarah yang sangat efektif untuk tujuan klasifikasi dan pengenalan pola, yang bertujuan untuk menemukan bidang pemisah terbaik (Hyperplane) yang memisahkan dua buah kelas pada ruang masukan dengan bekerja meminimalkan risiko empiris (Empirical Risk Minimization) dan meminimalkan risiko strutural (Structural Risk Minimization) yang meminimalkan kesalahan atau selisih antara nilai target pada himpunan data pelatihan dengan keluaran yang dihasilkan oleh model tersebut dan menghasilkan generalisasi yang baik untuk mengklasifikasikan data yang tidak terdapat dalam data pelatihan [22]. Gambar 2.1 menunjukkan beberapa pola yang merupakan anggota dari dua kelas, +1 dan -1, kelas 1 dengan simbol kotak warna merah untuk pola -1 dan kelas 2 dengan simbol lingkaran berwarna hijau untuk pola +1, terlihat juga sejumlah pilihan bidang pemisah yang mungkin. 

Kemampuan generalisasi suatu metode dalam mengklasifikasikan suatu pola yang tidak termasuk data yang dipakai dalam fase pembelajaran dipengaruhi oleh dua faktor yaitu kesalahan terhadap himpunan data latih dan faktor pengaruh dimensi VC (Vapnik-Chervonenkis). Kelebihan lain SVM adalah tingkat generalisasi yang diperoleh tidak dipengaruhi oleh dimensi dari vektor masukan dalam mengestimasikan parameter (jumlah neuron tersembunyi pada neural network, laju belajar, kriteria berhenti dalam peroses pembelajaran, dan sebagainya), dikarenakan jumlah sampel data yang relatif sedikit dibandingkan dengan ruang vektor data tersebut. 

### Tahapan SVM
tahapan ini merupakan...

### Modul Kuliah Minggu Ke 2 - Materi CSS
Dosen Pengampu : **Arif Wicaksono Septyanto**

Tujuan :
- Memahami dasar-dasar CSS dalam membangun sebuah Web.

Aturan Dasar Penulisan CSS
Cascading Style Sheets (CSS) digunakan untuk mengatur tampilan dan gaya elemen-elemen HTML di halaman web. Berikut adalah beberapa aturan dasar penulisan CSS:

Selektor: Selektor adalah elemen HTML yang ingin Anda gayakan. Misalnya, jika Anda ingin mengubah tampilan semua paragraf di halaman, maka ``<p>`` adalah selektornya.

Properti: Properti adalah atribut gaya yang ingin Anda terapkan pada elemen terpilih. Misalnya, untuk mengubah warna teks, properti yang digunakan adalah color.

Nilai Properti: Setiap properti memiliki nilai yang dapat Anda atur. Misalnya, untuk properti color, nilai bisa berupa nama warna (seperti "red" atau "blue") atau kode warna (seperti "#FF0000" untuk merah).

Deklarasi: Deklarasi adalah kombinasi dari properti dan nilai yang diterapkan pada selektor. Deklarasi ini ditempatkan di dalam blok gaya yang diapit oleh tanda kurung kurawal {}.

Contoh aturan dasar penulisan CSS:

```css
/* Selektor: Mengubah semua paragraf */
p {
  color: blue;
  font-size: 16px;
  margin: 10px;
}

/* Selektor: Mengubah elemen dengan class "highlight" */
.highlight {
  background-color: yellow;
  border: 1px solid black;
}

/* Selektor: Mengubah elemen dengan id "header" */
#header {
  text-align: center;
  font-size: 24px;
}
```
Dalam contoh di atas, Anda melihat penggunaan selektor seperti p, .highlight, dan #header. Setiap selektor diikuti oleh blok deklarasi yang berisi properti dan nilai yang ingin Anda terapkan pada elemen yang dipilih.

Beberapa aturan dasar tambahan yang perlu diingat:

1. Spasi dan Indentasi: Gunakan spasi atau tab untuk mengindentasi kode agar lebih mudah dibaca. Ini tidak mempengaruhi tampilan tetapi membuat kode lebih terstruktur.
2. Komentar: Anda dapat menambahkan komentar di CSS dengan menggunakan tanda /* komentar */. Komentar ini akan diabaikan oleh browser dan hanya berfungsi untuk keperluan dokumentasi.
3. Case Sensitivity: CSS bersifat case-insensitive untuk nama elemen dan atribut, tetapi case-sensitive untuk nama kelas, id, serta nama properti dan nilai.
4. Kaskade: Jika ada beberapa aturan CSS yang diterapkan pada elemen yang sama, maka aturan yang lebih spesifik atau yang terakhir dideklarasikan akan digunakan.
5. Unit: Nilai-nilai seperti ukuran font atau lebar harus diberikan dalam unit yang sesuai seperti px, em, rem, %, dll.


